name: CardScanClient
targets:
  CardScanClient:
    type: framework
    platform: iOS
    deploymentTarget: "11.0"
    sources: [CardScanClient]
    info:
      path: ./Info.plist
      version: 1.0.0
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
