/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.cardscan.client.models

import ai.cardscan.client.models.CardApiResponseDetails
import ai.cardscan.client.models.CardApiResponseImages
import ai.cardscan.client.models.CardState
import ai.cardscan.client.models.ModelError

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param cardId 
 * @param state 
 * @param createdAt The timestamp when the eligibility response was created.
 * @param deleted 
 * @param error 
 * @param images 
 * @param details 
 */
@Serializable

data class CardApiResponse (

    @Contextual @SerialName(value = "card_id")
    val cardId: java.util.UUID,

    @Contextual @SerialName(value = "state")
    val state: CardState,

    /* The timestamp when the eligibility response was created. */
    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @SerialName(value = "deleted")
    val deleted: kotlin.Boolean,

    @SerialName(value = "error")
    val error: ModelError? = null,

    @SerialName(value = "images")
    val images: CardApiResponseImages? = null,

    @SerialName(value = "details")
    val details: CardApiResponseDetails? = null

) {


}

