/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.cardscan.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param url The URL to the back image of the card.
 */
@Parcelize
@Serializable

data class CardApiResponseImagesBack (

    /* The URL to the back image of the card. */
    @Contextual @SerialName(value = "url")
    val url: java.net.URI? = null

) : Parcelable

