/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.cardscan.client.models

import ai.cardscan.client.models.Deductible
import ai.cardscan.client.models.OOP

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param individualDeductibleInNetwork 
 * @param individualOopInNetwork 
 * @param familyDeductibleInNetwork 
 * @param familyOopInNetwork 
 */
@Parcelize
@Serializable

data class CoverageSummary (

    @SerialName(value = "individual_deductible_in_network")
    val individualDeductibleInNetwork: Deductible? = null,

    @SerialName(value = "individual_oop_in_network")
    val individualOopInNetwork: OOP? = null,

    @SerialName(value = "family_deductible_in_network")
    val familyDeductibleInNetwork: Deductible? = null,

    @SerialName(value = "family_oop_in_network")
    val familyOopInNetwork: OOP? = null

) : Parcelable

