/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.cardscan.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param scanning The scanning mode
 */
@JsonClass(generateAdapter = true)

data class CreateCardRequestBackside (

    /* The scanning mode */
    @Json(name = "scanning")
    val scanning: CreateCardRequestBackside.Scanning? = Scanning.disabled

) {

    /**
     * The scanning mode
     *
     * Values: required,optional,disabled
     */
    @JsonClass(generateAdapter = false)
    enum class Scanning(val value: kotlin.String) {
        @Json(name = "required") required("required"),
        @Json(name = "optional") optional("optional"),
        @Json(name = "disabled") disabled("disabled");
    }

}

