/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.cardscan.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param totalAmount The total deductible amount.
 * @param remainingAmount The remaining deductible amount.
 */
@Serializable

data class Deductible (

    /* The total deductible amount. */
    @SerialName(value = "total_amount")
    val totalAmount: kotlin.String? = null,

    /* The remaining deductible amount. */
    @SerialName(value = "remaining_amount")
    val remainingAmount: kotlin.String? = null

) {


}

