/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.cardscan.client.models

import ai.cardscan.client.models.CardState
import ai.cardscan.client.models.WebsocketError

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param eventId 
 * @param type 
 * @param eligibilityId 
 * @param state 
 * @param createdAt 
 * @param sessionId 
 * @param error 
 * @param cardId 
 */
@JsonClass(generateAdapter = true)

data class EligibilityWebsocketEvent (

    @Json(name = "event_id")
    val eventId: kotlin.String,

    @Json(name = "type")
    val type: EligibilityWebsocketEvent.Type,

    @Json(name = "eligibility_id")
    val eligibilityId: kotlin.String,

    @Json(name = "state")
    val state: CardState,

    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "session_id")
    val sessionId: kotlin.String? = null,

    @Json(name = "error")
    val error: WebsocketError? = null,

    @Json(name = "card_id")
    val cardId: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: eligibility
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "eligibility") eligibility("eligibility");
    }

}

