/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.cardscan.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param firstName The first name of the subscriber.
 * @param lastName The last name of the subscriber.
 * @param memberId The member ID of the subscriber.
 * @param dob The date of birth of the subscriber.
 */
@Parcelize
@Serializable

data class EligibilityApiResponseEligibilityRequestSubscriber (

    /* The first name of the subscriber. */
    @SerialName(value = "firstName")
    val firstName: kotlin.String? = null,

    /* The last name of the subscriber. */
    @SerialName(value = "lastName")
    val lastName: kotlin.String? = null,

    /* The member ID of the subscriber. */
    @SerialName(value = "memberId")
    val memberId: kotlin.String? = null,

    /* The date of birth of the subscriber. */
    @SerialName(value = "dob")
    val dob: kotlin.String? = null

) : Parcelable

