/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.cardscan.client.models

import ai.cardscan.client.models.ApiErrorResponse
import ai.cardscan.client.models.CardState

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param eventId 
 * @param type 
 * @param eligibilityId 
 * @param state 
 * @param createdAt 
 * @param sessionId 
 * @param error 
 * @param cardId 
 */
@Parcelize
@Serializable

data class EligibilityWebsocketEvent (

    @SerialName(value = "event_id")
    val eventId: kotlin.String,

    @SerialName(value = "type")
    val type: EligibilityWebsocketEvent.Type,

    @SerialName(value = "eligibility_id")
    val eligibilityId: kotlin.String,

    @Contextual @SerialName(value = "state")
    val state: CardState,

    @Contextual @SerialName(value = "created_at")
    val createdAt: kotlinx.datetime.Instant,

    @SerialName(value = "session_id")
    val sessionId: kotlin.String? = null,

    @SerialName(value = "error")
    val error: ApiErrorResponse? = null,

    @SerialName(value = "card_id")
    val cardId: kotlin.String? = null

) : Parcelable {

    /**
     * 
     *
     * Values: eligibility
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "eligibility") eligibility("eligibility");
    }
}

