/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.cardscan.client.models

import ai.cardscan.client.models.UploadParameters

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param cardId 
 * @param scanId 
 * @param uploadUrl The URL to upload the card image.
 * @param uploadParameters 
 */
@Serializable

data class GenerateCardUploadUrl200Response (

    @Contextual @SerialName(value = "card_id")
    val cardId: java.util.UUID,

    @Contextual @SerialName(value = "scan_id")
    val scanId: java.util.UUID,

    /* The URL to upload the card image. */
    @Contextual @SerialName(value = "upload_url")
    val uploadUrl: java.net.URI,

    @SerialName(value = "upload_parameters")
    val uploadParameters: UploadParameters

) {


}

