/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.cardscan.client.models

import ai.cardscan.client.models.ScanCaptureType
import ai.cardscan.client.models.ScanMetadata
import ai.cardscan.client.models.ScanOrientation

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param orientation 
 * @param captureType 
 * @param metadata 
 */
@JsonClass(generateAdapter = true)

data class GenerateCardUploadUrlRequest (

    @Json(name = "orientation")
    val orientation: ScanOrientation,

    @Json(name = "capture_type")
    val captureType: ScanCaptureType? = null,

    @Json(name = "metadata")
    val metadata: ScanMetadata? = null

) {


}

