/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.cardscan.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param message A message describing the error.
 */
@Parcelize
@Serializable

data class GetAccessToken500Response (

    /* A message describing the error. */
    @SerialName(value = "message")
    val message: kotlin.String? = null

) : Parcelable

