/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.cardscan.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param token The access token.
 * @param identityId The identity ID.
 * @param sessionId The session ID.
 */
@Serializable

data class GetAccessToken200Response (

    /* The access token. */
    @SerialName(value = "Token")
    val token: kotlin.String,

    /* The identity ID. */
    @SerialName(value = "IdentityId")
    val identityId: kotlin.String,

    /* The session ID. */
    @SerialName(value = "session_id")
    val sessionId: kotlin.String? = null

) {


}

