/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.cardscan.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param message A message describing the error.
 */
@JsonClass(generateAdapter = true)

data class GetAccessToken500Response (

    /* A message describing the error. */
    @Json(name = "message")
    val message: kotlin.String? = null

) {


}

