/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.cardscan.client.models

import ai.cardscan.client.models.EligibilityApiResponse
import ai.cardscan.client.models.ResponseMetadata

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param eligibilityRequests 
 * @param responseMetadata 
 */
@Serializable

data class ListEligibility200Response (

    @SerialName(value = "eligibility_requests")
    val eligibilityRequests: kotlin.collections.List<EligibilityApiResponse>,

    @SerialName(value = "response_metadata")
    val responseMetadata: ResponseMetadata

) {


}

