/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.cardscan.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * Dimensions of the capture canvas
 *
 * @param width 
 * @param height 
 */
@Parcelize
@Serializable

data class ScanMetadataCaptureCanvas (

    @SerialName(value = "width")
    val width: kotlin.Int? = null,

    @SerialName(value = "height")
    val height: kotlin.Int? = null

) : Parcelable

