/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.cardscan.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param score 
 * @param laplacian 
 */
@Parcelize
@Serializable

data class ScanMetadataCaptureScoreScoresInner (

    @Contextual @SerialName(value = "score")
    val score: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "laplacian")
    val laplacian: java.math.BigDecimal? = null

) : Parcelable

