/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.cardscan.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Video track details
 *
 * @param aspectRatio 
 * @param deviceId 
 * @param frameRate 
 * @param groupId 
 * @param height 
 * @param resizeMode 
 * @param width 
 */
@Serializable

data class ScanMetadataVideoTrack (

    @Contextual @SerialName(value = "aspectRatio")
    val aspectRatio: java.math.BigDecimal? = null,

    @SerialName(value = "deviceId")
    val deviceId: kotlin.String? = null,

    @Contextual @SerialName(value = "frameRate")
    val frameRate: java.math.BigDecimal? = null,

    @SerialName(value = "groupId")
    val groupId: kotlin.String? = null,

    @SerialName(value = "height")
    val height: kotlin.Int? = null,

    @SerialName(value = "resizeMode")
    val resizeMode: kotlin.String? = null,

    @SerialName(value = "width")
    val width: kotlin.Int? = null

) {


}

