/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.cardscan.client.models

import ai.cardscan.client.models.CardApiResponse
import ai.cardscan.client.models.ResponseMetadata

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param cards 
 * @param responseMetadata 
 */
@JsonClass(generateAdapter = true)

data class SearchCards200Response (

    @Json(name = "cards")
    val cards: kotlin.collections.List<CardApiResponse>,

    @Json(name = "response_metadata")
    val responseMetadata: ResponseMetadata

) {


}

