/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.cardscan.client.models

import ai.cardscan.client.models.CoInsurance
import ai.cardscan.client.models.CoPayment
import ai.cardscan.client.models.Deductible
import ai.cardscan.client.models.OOP

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param individualDeductibleInNetwork 
 * @param individualDeductibleOutNetwork 
 * @param individualOopInNetwork 
 * @param individualOopOutNetwork 
 * @param familyDeductibleInNetwork 
 * @param familyDeductibleOutNetwork 
 * @param familyOopInNetwork 
 * @param familyOopOutNetwork 
 * @param coInsuranceInNetwork 
 * @param coInsuranceOutNetwork 
 * @param coPaymentOutNetwork 
 * @param coPaymentInNetwork 
 * @param serviceCode The service code.
 */
@Serializable

data class Service (

    @SerialName(value = "individual_deductible_in_network")
    val individualDeductibleInNetwork: Deductible? = null,

    @SerialName(value = "individual_deductible_out_network")
    val individualDeductibleOutNetwork: Deductible? = null,

    @SerialName(value = "individual_oop_in_network")
    val individualOopInNetwork: OOP? = null,

    @SerialName(value = "individual_oop_out_network")
    val individualOopOutNetwork: OOP? = null,

    @SerialName(value = "family_deductible_in_network")
    val familyDeductibleInNetwork: Deductible? = null,

    @SerialName(value = "family_deductible_out_network")
    val familyDeductibleOutNetwork: Deductible? = null,

    @SerialName(value = "family_oop_in_network")
    val familyOopInNetwork: OOP? = null,

    @SerialName(value = "family_oop_out_network")
    val familyOopOutNetwork: OOP? = null,

    @SerialName(value = "co_insurance_in_network")
    val coInsuranceInNetwork: CoInsurance? = null,

    @SerialName(value = "co_insurance_out_network")
    val coInsuranceOutNetwork: CoInsurance? = null,

    @SerialName(value = "co_payment_out_network")
    val coPaymentOutNetwork: CoPayment? = null,

    @SerialName(value = "co_payment_in_network")
    val coPaymentInNetwork: CoPayment? = null,

    /* The service code. */
    @SerialName(value = "service_code")
    val serviceCode: kotlin.String? = null

) {


}

