/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.cardscan.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param token The token associated with the magic link
 * @param identityId The identity ID.
 */
@Serializable

data class ValidateMagicLink200Response (

    /* The token associated with the magic link */
    @SerialName(value = "Token")
    val token: kotlin.String,

    /* The identity ID. */
    @SerialName(value = "IdentityId")
    val identityId: kotlin.String

) {


}

