//
// EligibilityInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EligibilityInfo: Codable, JSONEncodable, Hashable {

    public var provider: ProviderDto
    public var subscriber: SubscriberDto

    public init(provider: ProviderDto, subscriber: SubscriberDto) {
        self.provider = provider
        self.subscriber = subscriber
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case provider
        case subscriber
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(provider, forKey: .provider)
        try container.encode(subscriber, forKey: .subscriber)
    }
}

