//
// ScanMetadataCameraCapabilities.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Camera capabilities */
public struct ScanMetadataCameraCapabilities: Codable, JSONEncodable, Hashable {

    public var aspectRatio: ScanMetadataCameraCapabilitiesAspectRatio?
    public var deviceId: String?
    public var facingMode: [String]?
    public var frameRate: ScanMetadataCameraCapabilitiesAspectRatio?
    public var groupId: String?
    public var height: ScanMetadataCameraCapabilitiesAspectRatio?
    public var resizeMode: [String]?
    public var width: ScanMetadataCameraCapabilitiesAspectRatio?

    public init(aspectRatio: ScanMetadataCameraCapabilitiesAspectRatio? = nil, deviceId: String? = nil, facingMode: [String]? = nil, frameRate: ScanMetadataCameraCapabilitiesAspectRatio? = nil, groupId: String? = nil, height: ScanMetadataCameraCapabilitiesAspectRatio? = nil, resizeMode: [String]? = nil, width: ScanMetadataCameraCapabilitiesAspectRatio? = nil) {
        self.aspectRatio = aspectRatio
        self.deviceId = deviceId
        self.facingMode = facingMode
        self.frameRate = frameRate
        self.groupId = groupId
        self.height = height
        self.resizeMode = resizeMode
        self.width = width
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case aspectRatio
        case deviceId
        case facingMode
        case frameRate
        case groupId
        case height
        case resizeMode
        case width
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(aspectRatio, forKey: .aspectRatio)
        try container.encodeIfPresent(deviceId, forKey: .deviceId)
        try container.encodeIfPresent(facingMode, forKey: .facingMode)
        try container.encodeIfPresent(frameRate, forKey: .frameRate)
        try container.encodeIfPresent(groupId, forKey: .groupId)
        try container.encodeIfPresent(height, forKey: .height)
        try container.encodeIfPresent(resizeMode, forKey: .resizeMode)
        try container.encodeIfPresent(width, forKey: .width)
    }
}

