//
// ScanMetadataCaptureScore.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ScanMetadataCaptureScore: Codable, JSONEncodable, Hashable {

    /** List of capture scores */
    public var scores: [ScanMetadataCaptureScoreScoresInner]?
    /** Maximum Laplacian score */
    public var maxLapScore: Double?

    public init(scores: [ScanMetadataCaptureScoreScoresInner]? = nil, maxLapScore: Double? = nil) {
        self.scores = scores
        self.maxLapScore = maxLapScore
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case scores
        case maxLapScore = "max_lapScore"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(scores, forKey: .scores)
        try container.encodeIfPresent(maxLapScore, forKey: .maxLapScore)
    }
}

