name: cardscan_client
version: 1.0.0
description: Official CardScan API client
homepage: https://cardscan.ai

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  dio: ^5.7.0
  one_of: '>=1.5.0 <2.0.0'
  one_of_serializer: '>=1.5.0 <2.0.0'
  built_value: '>=8.10.1 <9.0.0'
  built_collection: '>=5.1.1 <6.0.0'

dev_dependencies:
  built_value_generator: '>=8.10.1 <9.0.0'
  build_runner: ^2.4.15
  test: '>=1.26.2 <1.27.0'
