//
// ApiErrorResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ApiErrorResponse: Codable, JSONEncodable, Hashable {

    /** A message describing the error. */
    public var message: String?
    /** The type of error. */
    public var type: String?
    /** The error code. */
    public var code: Double?

    public init(message: String? = nil, type: String? = nil, code: Double? = nil) {
        self.message = message
        self.type = type
        self.code = code
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case type
        case code
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(code, forKey: .code)
    }
}

