//
// CardApiResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CardApiResponse: Codable, JSONEncodable, Hashable {

    public var cardId: UUID
    public var state: CardState
    /** The timestamp when the eligibility response was created. */
    public var createdAt: Date
    public var error: ApiErrorResponse?
    public var images: CardApiResponseImages?
    public var deleted: Bool
    public var details: CardApiResponseDetails?

    public init(cardId: UUID, state: CardState, createdAt: Date, error: ApiErrorResponse? = nil, images: CardApiResponseImages? = nil, deleted: Bool, details: CardApiResponseDetails? = nil) {
        self.cardId = cardId
        self.state = state
        self.createdAt = createdAt
        self.error = error
        self.images = images
        self.deleted = deleted
        self.details = details
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cardId = "card_id"
        case state
        case createdAt = "created_at"
        case error
        case images
        case deleted
        case details
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(cardId, forKey: .cardId)
        try container.encode(state, forKey: .state)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(error, forKey: .error)
        try container.encodeIfPresent(images, forKey: .images)
        try container.encode(deleted, forKey: .deleted)
        try container.encodeIfPresent(details, forKey: .details)
    }
}

