//
// CardApiResponseImages.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CardApiResponseImages: Codable, JSONEncodable, Hashable {

    public var front: CardApiResponseImagesFront?
    public var back: CardApiResponseImagesBack?

    public init(front: CardApiResponseImagesFront? = nil, back: CardApiResponseImagesBack? = nil) {
        self.front = front
        self.back = back
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case front
        case back
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(front, forKey: .front)
        try container.encodeIfPresent(back, forKey: .back)
    }
}

