//
// CopayCategory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum CopayCategory: String, Codable, CaseIterable {
    case copay = "copay"
    case coinsurance = "coinsurance"
    case deductible = "deductible"
    case outOfPocketMax = "out_of_pocket_max"
    case other = "other"
}
