//
// DirectUpload200ResponseMetadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DirectUpload200ResponseMetadata: Codable, JSONEncodable, Hashable {

    /** OCR latency in milliseconds */
    public var ocrLatency: String?

    public init(ocrLatency: String? = nil) {
        self.ocrLatency = ocrLatency
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ocrLatency = "ocr_latency"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(ocrLatency, forKey: .ocrLatency)
    }
}

