//
// EligibilityApiResponseError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Details about any error that occurred during the request. (Only first error) */
public struct EligibilityApiResponseError: Codable, JSONEncodable, Hashable {

    /** The type of error. */
    public var type: String?
    /** The error code. */
    public var code: String?
    /** A message describing the error. */
    public var message: String?

    public init(type: String? = nil, code: String? = nil, message: String? = nil) {
        self.type = type
        self.code = code
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case code
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(code, forKey: .code)
        try container.encodeIfPresent(message, forKey: .message)
    }
}

