//
// EnrichedPhoneNumberResultInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EnrichedPhoneNumberResultInner: Codable, JSONEncodable, Hashable {

    /** The label or description of the phone number (e.g., \"Member Services\", \"Providers Call\") */
    public var label: String
    public var type: PhoneNumberType
    /** The phone number in NPA-NXX-XXXX format */
    public var number: String
    /** Confidence score for the extraction (0-1 as string) */
    public var score: String

    public init(label: String, type: PhoneNumberType, number: String, score: String) {
        self.label = label
        self.type = type
        self.number = number
        self.score = score
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case label
        case type
        case number
        case score
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(label, forKey: .label)
        try container.encode(type, forKey: .type)
        try container.encode(number, forKey: .number)
        try container.encode(score, forKey: .score)
    }
}

