//
// GenerateMagicLink200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GenerateMagicLink200Response: Codable, JSONEncodable, Hashable {

    /** The URL of the magic link */
    public var magicLink: String
    /** The token associated with the magic link */
    public var token: String
    /** The expiration date and time of the magic link */
    public var expiresAt: Date

    public init(magicLink: String, token: String, expiresAt: Date) {
        self.magicLink = magicLink
        self.token = token
        self.expiresAt = expiresAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case magicLink = "magic_link"
        case token
        case expiresAt = "expires_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(magicLink, forKey: .magicLink)
        try container.encode(token, forKey: .token)
        try container.encode(expiresAt, forKey: .expiresAt)
    }
}

