//
// GenerateCardUploadUrlRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GenerateCardUploadUrlRequest: Codable, JSONEncodable, Hashable {

    public var orientation: ScanOrientation
    public var captureType: ScanCaptureType?
    public var metadata: ScanMetadata?

    public init(orientation: ScanOrientation, captureType: ScanCaptureType? = nil, metadata: ScanMetadata? = nil) {
        self.orientation = orientation
        self.captureType = captureType
        self.metadata = metadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case orientation
        case captureType = "capture_type"
        case metadata
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(orientation, forKey: .orientation)
        try container.encodeIfPresent(captureType, forKey: .captureType)
        try container.encodeIfPresent(metadata, forKey: .metadata)
    }
}

