//
// ListEligibility200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListEligibility200Response: Codable, JSONEncodable, Hashable {

    public var eligibilityRequests: [EligibilityApiResponse]
    public var responseMetadata: ResponseMetadata

    public init(eligibilityRequests: [EligibilityApiResponse], responseMetadata: ResponseMetadata) {
        self.eligibilityRequests = eligibilityRequests
        self.responseMetadata = responseMetadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case eligibilityRequests = "eligibility_requests"
        case responseMetadata = "response_metadata"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(eligibilityRequests, forKey: .eligibilityRequests)
        try container.encode(responseMetadata, forKey: .responseMetadata)
    }
}

