//
// WebhookCardErrorEvent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Triggered when an error occurs during a card scan. */
public struct WebhookCardErrorEvent: Codable, JSONEncodable, Hashable {

    /** Unique identifier for the card. */
    public var cardId: UUID
    /** Timestamp for when the card was created. */
    public var createdAt: Date
    /** Flag indicating whether the card is deleted. */
    public var deleted: Bool
    public var error: WebhookCardErrorEventError
    /** Unique identifier for the session. */
    public var sessionId: String
    /** Type of event. */
    public var type: String
    /** Timestamp for the last update. */
    public var updatedAt: Date
    /** Identifier for the user associated with the event. */
    public var userId: String

    public init(cardId: UUID, createdAt: Date, deleted: Bool, error: WebhookCardErrorEventError, sessionId: String, type: String, updatedAt: Date, userId: String) {
        self.cardId = cardId
        self.createdAt = createdAt
        self.deleted = deleted
        self.error = error
        self.sessionId = sessionId
        self.type = type
        self.updatedAt = updatedAt
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cardId = "card_id"
        case createdAt = "created_at"
        case deleted
        case error
        case sessionId = "session_id"
        case type
        case updatedAt = "updated_at"
        case userId = "user_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(cardId, forKey: .cardId)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(deleted, forKey: .deleted)
        try container.encode(error, forKey: .error)
        try container.encode(sessionId, forKey: .sessionId)
        try container.encode(type, forKey: .type)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(userId, forKey: .userId)
    }
}

