/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: medical_claims_address,pharmacy_claims_address,vision_claims_address,dental_claims_address,appeals_address,pcp_address,general_address
 */

@JsonClass(generateAdapter = false)
enum class AddressType(val value: kotlin.String) {

    @Json(name = "medical_claims_address")
    medical_claims_address("medical_claims_address"),

    @Json(name = "pharmacy_claims_address")
    pharmacy_claims_address("pharmacy_claims_address"),

    @Json(name = "vision_claims_address")
    vision_claims_address("vision_claims_address"),

    @Json(name = "dental_claims_address")
    dental_claims_address("dental_claims_address"),

    @Json(name = "appeals_address")
    appeals_address("appeals_address"),

    @Json(name = "pcp_address")
    pcp_address("pcp_address"),

    @Json(name = "general_address")
    general_address("general_address");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is AddressType) "$data" else null

        /**
         * Returns a valid [AddressType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): AddressType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

