/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CardState
import org.openapitools.client.models.WebsocketError

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param eventId 
 * @param type 
 * @param cardId 
 * @param state 
 * @param createdAt 
 * @param sessionId 
 * @param error 
 */


data class CardWebsocketEvent (

    @Json(name = "event_id")
    val eventId: kotlin.String,

    @Json(name = "type")
    val type: CardWebsocketEvent.Type,

    @Json(name = "card_id")
    val cardId: java.util.UUID,

    @Json(name = "state")
    val state: CardState,

    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "session_id")
    val sessionId: kotlin.String? = null,

    @Json(name = "error")
    val error: WebsocketError? = null

) {

    /**
     * 
     *
     * Values: card
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "card") card("card");
    }

}

