/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.UploadParameters

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param cardId 
 * @param scanId 
 * @param uploadUrl The URL to upload the card image.
 * @param uploadParameters 
 */


data class GenerateCardUploadUrl200Response (

    @Json(name = "card_id")
    val cardId: java.util.UUID,

    @Json(name = "scan_id")
    val scanId: java.util.UUID,

    /* The URL to upload the card image. */
    @Json(name = "upload_url")
    val uploadUrl: java.net.URI,

    @Json(name = "upload_parameters")
    val uploadParameters: UploadParameters

) {


}

