/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param totalAmount The total out-of-pocket amount.
 * @param remainingAmount The remaining out-of-pocket amount.
 */


data class OOP (

    /* The total out-of-pocket amount. */
    @Json(name = "total_amount")
    val totalAmount: kotlin.String? = null,

    /* The remaining out-of-pocket amount. */
    @Json(name = "remaining_amount")
    val remainingAmount: kotlin.String? = null

) {


}

