/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param lastUpdated 
 * @param source 
 */


data class PayerMatchMatchesInnerMetadata (

    @Json(name = "last_updated")
    val lastUpdated: kotlin.String? = null,

    @Json(name = "source")
    val source: kotlin.String? = null

) {


}

