/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Details about the error encountered during the scan.
 *
 * @param error Error type or identifier.
 * @param message Detailed error message.
 */


data class WebhookCardErrorEventError (

    /* Error type or identifier. */
    @Json(name = "error")
    val error: kotlin.String,

    /* Detailed error message. */
    @Json(name = "message")
    val message: kotlin.String

) {


}

