# coding: utf-8

"""
    CardScan API

    The official documentation for the CardScan API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.card_api_response_details import CardApiResponseDetails  # noqa: E501

class TestCardApiResponseDetails(unittest.TestCase):
    """CardApiResponseDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CardApiResponseDetails:
        """Test CardApiResponseDetails
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CardApiResponseDetails`
        """
        model = CardApiResponseDetails()  # noqa: E501
        if include_optional:
            return CardApiResponseDetails(
                group_number = openapi_client.models.match_score.MatchScore(
                    value = 1.337, 
                    scores = [
                        ''
                        ], ),
                member_number = openapi_client.models.match_score.MatchScore(
                    value = 1.337, 
                    scores = [
                        ''
                        ], ),
                payer_name = openapi_client.models.match_score.MatchScore(
                    value = 1.337, 
                    scores = [
                        ''
                        ], ),
                rx_bin = openapi_client.models.match_score.MatchScore(
                    value = 1.337, 
                    scores = [
                        ''
                        ], ),
                rx_pcn = openapi_client.models.match_score.MatchScore(
                    value = 1.337, 
                    scores = [
                        ''
                        ], ),
                member_name = openapi_client.models.match_score.MatchScore(
                    value = 1.337, 
                    scores = [
                        ''
                        ], ),
                dependent_names = [
                    openapi_client.models.match_score.MatchScore(
                        value = 1.337, 
                        scores = [
                            ''
                            ], )
                    ],
                plan_name = openapi_client.models.match_score.MatchScore(
                    value = 1.337, 
                    scores = [
                        ''
                        ], ),
                plan_id = openapi_client.models.match_score.MatchScore(
                    value = 1.337, 
                    scores = [
                        ''
                        ], ),
                card_specific_id = openapi_client.models.match_score.MatchScore(
                    value = 1.337, 
                    scores = [
                        ''
                        ], )
            )
        else:
            return CardApiResponseDetails(
        )
        """

    def testCardApiResponseDetails(self):
        """Test CardApiResponseDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
