# coding: utf-8

"""
    CardScan API

    The official documentation for the CardScan API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.benefits_related_entity import BenefitsRelatedEntity  # noqa: E501

class TestBenefitsRelatedEntity(unittest.TestCase):
    """BenefitsRelatedEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BenefitsRelatedEntity:
        """Test BenefitsRelatedEntity
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BenefitsRelatedEntity`
        """
        model = BenefitsRelatedEntity()  # noqa: E501
        if include_optional:
            return BenefitsRelatedEntity(
                entity_identifier = '',
                entity_type = '',
                entity_name = '',
                entity_firstname = '',
                entity_middlename = '',
                entity_suffix = '',
                entity_identification = '',
                entity_identification_value = '',
                entity_relationship = '',
                address = openapi_client.models.address.Address(
                    address1 = '123 address1', 
                    address2 = '', 
                    city = 'city1', 
                    state = 'wa', 
                    postal_code = '981010000', 
                    country_code = '', 
                    location_identifier = '', 
                    country_sub_division_code = '', ),
                contact_information = openapi_client.models.contact_information.ContactInformation(
                    name = '', 
                    contacts = [
                        openapi_client.models.contacts.Contacts(
                            communication_mode = '', 
                            communication_number = '', )
                        ], ),
                provider_information = openapi_client.models.provider_information.ProviderInformation(
                    provider_code = '', 
                    reference_identification = '', )
            )
        else:
            return BenefitsRelatedEntity(
        )
        """

    def testBenefitsRelatedEntity(self):
        """Test BenefitsRelatedEntity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
