# coding: utf-8

"""
    CardScan API

    The official documentation for the CardScan API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.upload_parameters import UploadParameters  # noqa: E501

class TestUploadParameters(unittest.TestCase):
    """UploadParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UploadParameters:
        """Test UploadParameters
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UploadParameters`
        """
        model = UploadParameters()  # noqa: E501
        if include_optional:
            return UploadParameters(
                key = '',
                x_amz_algorithm = '',
                x_amz_credential = '',
                x_amz_date = '',
                x_amz_security_token = '',
                policy = '',
                x_amz_signature = ''
            )
        else:
            return UploadParameters(
                key = '',
                x_amz_algorithm = '',
                x_amz_credential = '',
                x_amz_date = '',
                x_amz_security_token = '',
                policy = '',
                x_amz_signature = '',
        )
        """

    def testUploadParameters(self):
        """Test UploadParameters"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
