# coding: utf-8

"""
    CardScan API

    The official documentation for the CardScan API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.plan_information import PlanInformation  # noqa: E501

class TestPlanInformation(unittest.TestCase):
    """PlanInformation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlanInformation:
        """Test PlanInformation
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlanInformation`
        """
        model = PlanInformation()  # noqa: E501
        if include_optional:
            return PlanInformation(
                state_license_number = '',
                medicare_provider_number = '',
                medicaid_provider_number = '',
                facility_id_number = '',
                personal_identification_number = '',
                plan_number = '',
                plan_description = '',
                policy_number = '',
                member_id = '',
                case_number = '',
                family_unit_number = '',
                group_number = '',
                group_description = '',
                referral_number = '',
                alternative_list_id = '',
                class_of_contract_code = '',
                coverage_list_id = '',
                contract_number = '',
                medical_record_identification_number = '',
                electronic_device_pin = '',
                submitter_identification_number = '',
                patient_account_number = '',
                hic_number = '',
                drug_formulary_number = '',
                prior_authorization_number = '',
                id_card_serial_number = '',
                id_card_number = '',
                centers_for_medicare_and_medicaid_services_npi = '',
                issue_number = '',
                insurance_policy_number = '',
                user_identification = '',
                medical_assistance_category = '',
                eligibility_category = '',
                plan_network_id_number = '',
                plan_network_id_description = '',
                facility_network_identification_number = '',
                medicaid_recipient_id_number = '',
                prior_id_number = '',
                social_security_number = '',
                federal_taxpayers_identification_number = '',
                agency_claim_number = ''
            )
        else:
            return PlanInformation(
        )
        """

    def testPlanInformation(self):
        """Test PlanInformation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
