/* tslint:disable */
/* eslint-disable */
/**
 * CardScan API
 * The official documentation for the CardScan API Clients.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



import { KeysToCamelCase, KeysToSnakeCase } from "./";

/**
 * 
 * @export
 * @interface Address
 */
export interface AddressOriginal {
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'address1'?: string;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'address2'?: string;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'state'?: string;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'postal_code'?: string;
}
export type Address = KeysToCamelCase<AddressOriginal>;
export type AddressSnake = KeysToSnakeCase<AddressOriginal>;


