/* tslint:disable */
/* eslint-disable */
/**
 * CardScan API
 * The official documentation for the CardScan API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



import { KeysToCamelCase } from "./";

/**
 * 
 * @export
 * @interface CardApiResponseImagesFront
 */
export interface CardApiResponseImagesFrontSnake {
    /**
     * The URL to the front image of the card.
     * @type {string}
     * @memberof CardApiResponseImagesFront
     */
    'url'?: string;
}
export type CardApiResponseImagesFront = KeysToCamelCase<CardApiResponseImagesFrontSnake>;


