/* tslint:disable */
/* eslint-disable */
/**
 * CardScan API
 * The official documentation for the CardScan API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CoInsurance
 */
export interface CoInsurance {
    /**
     * The co-insurance amount.
     * @type {string}
     * @memberof CoInsurance
     */
    'amount'?: string;
}

