/* tslint:disable */
/* eslint-disable */
/**
 * CardScan API
 * The official documentation for the CardScan API.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { DirectUpload200ResponseMetadata } from "./direct-upload200-response-metadata";

import { KeysToCamelCase } from "./";

/**
 *
 * @export
 * @interface DirectUpload200Response
 */
export interface DirectUpload200Response {
  /**
   *
   * @type {string}
   * @memberof DirectUpload200Response
   */
  card_id: string;
  /**
   *
   * @type {string}
   * @memberof DirectUpload200Response
   */
  scan_id: string;
  /**
   *
   * @type {DirectUpload200ResponseMetadata}
   * @memberof DirectUpload200Response
   */
  metadata: DirectUpload200ResponseMetadata;
}
export type DirectUpload200ResponseCamel =
  KeysToCamelCase<DirectUpload200Response>;
