/* tslint:disable */
/* eslint-disable */
/**
 * CardScan API
 * The official documentation for the CardScan API Clients.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { EligibilityApiResponseEligibilityRequest } from './eligibility-api-response-eligibility-request';
// May contain unused imports in some cases
// @ts-ignore
import { EligibilitySummarizedResponse } from './eligibility-summarized-response';
// May contain unused imports in some cases
// @ts-ignore
import { ModelError } from './model-error';

import { KeysToCamelCase, KeysToSnakeCase } from "./";

/**
 * 
 * @export
 * @interface EligibilityApiResponse
 */
export interface EligibilityApiResponseOriginal {
    /**
     * The ID of the eligibility record.
     * @type {string}
     * @memberof EligibilityApiResponse
     */
    'eligibility_id': string;
    /**
     * The state of the eligibility record.
     * @type {string}
     * @memberof EligibilityApiResponse
     */
    'state': EligibilityApiResponseStateEnum;
    /**
     * The ID of the card.
     * @type {string}
     * @memberof EligibilityApiResponse
     */
    'card_id': string;
    /**
     * 
     * @type {EligibilityApiResponseEligibilityRequest}
     * @memberof EligibilityApiResponse
     */
    'eligibility_request'?: EligibilityApiResponseEligibilityRequest;
    /**
     * The eligibility raw response.
     * @type {{ [key: string]: any; }}
     * @memberof EligibilityApiResponse
     */
    'eligibility_response'?: { [key: string]: any; } | null;
    /**
     * 
     * @type {EligibilitySummarizedResponse}
     * @memberof EligibilityApiResponse
     */
    'eligibility_summarized_response'?: EligibilitySummarizedResponse;
    /**
     * 
     * @type {ModelError}
     * @memberof EligibilityApiResponse
     */
    'error'?: ModelError;
    /**
     * The timestamp when the eligibility record was created.
     * @type {string}
     * @memberof EligibilityApiResponse
     */
    'created_at': string;
}

export const EligibilityApiResponseStateEnum = {
    Completed: 'completed',
    Processing: 'processing',
    Error: 'error'
} as const;

export type EligibilityApiResponseStateEnum = typeof EligibilityApiResponseStateEnum[keyof typeof EligibilityApiResponseStateEnum];

export type EligibilityApiResponse = KeysToCamelCase<EligibilityApiResponseOriginal>;
export type EligibilityApiResponseSnake = KeysToSnakeCase<EligibilityApiResponseOriginal>;


