/* tslint:disable */
/* eslint-disable */
/**
 * CardScan API
 * The official documentation for the CardScan API.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { CoverageSummary } from "./coverage-summary";
// May contain unused imports in some cases
// @ts-ignore
import { PayerDetails } from "./payer-details";
// May contain unused imports in some cases
// @ts-ignore
import { PlanDetails } from "./plan-details";
// May contain unused imports in some cases
// @ts-ignore
import { Service } from "./service";
// May contain unused imports in some cases
// @ts-ignore
import { SubscriberDetails } from "./subscriber-details";

import { KeysToCamelCase } from "./";

/**
 *
 * @export
 * @interface EligibilitySummarizedResponse
 */
export interface EligibilitySummarizedResponse {
  /**
   *
   * @type {SubscriberDetails}
   * @memberof EligibilitySummarizedResponse
   */
  subscriber_details?: SubscriberDetails;
  /**
   *
   * @type {PayerDetails}
   * @memberof EligibilitySummarizedResponse
   */
  payer_details?: PayerDetails;
  /**
   *
   * @type {PlanDetails}
   * @memberof EligibilitySummarizedResponse
   */
  plan_details?: PlanDetails;
  /**
   *
   * @type {CoverageSummary}
   * @memberof EligibilitySummarizedResponse
   */
  coverage_summary?: CoverageSummary;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  abortion?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  acupuncture?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  adjunctive_dental_services?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  aids?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  air_transportation?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  alcoholism?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  allergy?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  allergy_testing?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  alternate_method_dialysis?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  ambulatory_service_center_facility?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  anesthesia?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  anesthesiologist?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  audiology_exam?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  blood_charges?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  brand_name_prescription_drug?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  brand_name_prescription_drug_formulary?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  brand_name_prescription_drug_non_formulary?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  burn_care?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  cabulance?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  cancer?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  cardiac?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  cardiac_rehabilitation?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  case_management?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  chemotherapy?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  chiropractic?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  chiropractic_office_visits?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  chronic_renal_disease_crd_equipment?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  cognitive_therapy?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  consultation?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  coronary_care?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  day_care_psychiatric?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  dental_accident?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  dental_care?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  dental_crowns?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  dermatology?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  diabetic_supplies?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  diagnostic_dental?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  diagnostic_lab?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  diagnostic_medical?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  diagnostic_x_ray?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  dialysis?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  donor_procedures?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  drug_addiction?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  durable_medical_equipment?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  durable_medical_equipment_purchase?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  durable_medical_equipment_rental?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  emergency_room?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  endocrine?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  endodontics?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  experimental_drug_therapy?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  eye?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  eyewear_and_eyewear_accessories?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  family_planning?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  flu_vaccination?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  frames?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  free_standing_prescription_drug?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  gastrointestinal?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  general_benefits?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  generic_prescription_drug?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  generic_prescription_drug_formulary?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  generic_prescription_drug_non_formulary?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  gynecological?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  home_health_care?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  home_health_prescriptions?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  home_health_visits?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  hospice?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  hospital_inpatient?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  hospital_ambulatory_surgical?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  hospital_emergency_accident?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  hospital_emergency_medical?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  hospital_outpatient?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  hospital_room_and_board?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  immunizations?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  in_vitro_fertilization?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  independent_medical_evaluation?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  infertility?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  inhalation_therapy?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  intensive_care?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  invasive_procedures?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  lenses?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  licensed_ambulance?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  long_term_care?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  lymphatic?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  mail_order_prescription_drug?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  mail_order_prescription_drug_brand_name?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  mail_order_prescription_drug_generic?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  major_medical?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  mammogram_high_risk_patient?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  mammogram_low_risk_patient?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  massage_therapy?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  maternity?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  maxillofacial_prosthetics?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  medical_care?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  medically_related_transportation?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  mental_health?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  mental_health_facility_inpatient?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  mental_health_facility_outpatient?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  mental_health_provider_inpatient?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  mental_health_provider_outpatient?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  mri_cat_scan?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  neonatal_intensive_care?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  neurology?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  newborn_care?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  nonmedically_necessary_physical?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  nursery?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  obstetrical?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  obstetrical_gynecological?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  occupational_therapy?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  oncology?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  oral_surgery?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  orthodontics?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  orthopedic?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  other_medical?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  otological_exam?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  partial_hospitalization_psychiatric?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  pathology?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  pediatric?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  periodontics?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  pharmacy?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  physical_medicine?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  physical_therapy?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  physician_visit_office_sick?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  physician_visit_office_well?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  plan_waiting_period?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  pneumonia_vaccine?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  podiatry?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  podiatry_nursing_home_visits?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  podiatry_office_visits?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  pre_admission_testing?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  private_duty_nursing?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  private_duty_nursing_home?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  private_duty_nursing_inpatient?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  professional_physician?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  professional_physician_visit_home?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  professional_physician_visit_inpatient?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  professional_physician_visit_nursing_home?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  office_visit?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  professional_physician_visit_outpatient?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  professional_physician_visit_skilled_nursing?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  prosthetic_device?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  prosthodontics?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  psychiatric?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  psychiatric_inpatient?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  psychiatric_outpatient?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  psychiatric_room_and_board?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  psychotherapy?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  pulmonary?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  pulmonary_rehabilitation?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  radiation_therapy?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  rehabilitation?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  rehabilitation_inpatient?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  rehabilitation_outpatient?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  rehabilitation_room_and_board?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  renal?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  renal_supplies_in_the_home?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  residential_psychiatric_treatment?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  respite_care?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  restorative?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  routine_preventive_dental?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  routine_exam_use_for_routine_vision_exam_only?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  routine_physical?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  screening_laboratory?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  screening_x_ray?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  second_surgical_opinion?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  skilled_nursing_care?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  skilled_nursing_care_room_and_board?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  skin?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  smoking_cessation?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  social_work?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  speech_therapy?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  substance_abuse?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  substance_abuse_facility_inpatient?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  substance_abuse_facility_outpatient?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  substance_abuse_provider_inpatient?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  substance_abuse_provider_outpatient?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  surgical?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  surgical_assistance?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  surgical_benefits_facility?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  surgical_benefits_professional_physician?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  third_surgical_opinion?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  transitional_care?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  transitional_nursery_care?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  transplants?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  urgent_care?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  used_durable_medical_equipment?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  vision?: Service;
  /**
   *
   * @type {Service}
   * @memberof EligibilitySummarizedResponse
   */
  well_baby_care?: Service;
}
export type EligibilitySummarizedResponseCamel =
  KeysToCamelCase<EligibilitySummarizedResponse>;
