/* tslint:disable */
/* eslint-disable */
/**
 * CardScan API
 * The official documentation for the CardScan API.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { CardState } from "./card-state";
// May contain unused imports in some cases
// @ts-ignore
import { WebsocketError } from "./websocket-error";

import { KeysToCamelCase } from "./";

/**
 *
 * @export
 * @interface EligibilityWebsocketEvent
 */
export interface EligibilityWebsocketEventSnake {
  /**
   *
   * @type {string}
   * @memberof EligibilityWebsocketEvent
   */
  event_id: string;
  /**
   *
   * @type {string}
   * @memberof EligibilityWebsocketEvent
   */
  type: EligibilityWebsocketEventTypeEnum;
  /**
   *
   * @type {string}
   * @memberof EligibilityWebsocketEvent
   */
  eligibility_id: string;
  /**
   *
   * @type {CardState}
   * @memberof EligibilityWebsocketEvent
   */
  state: CardState;
  /**
   *
   * @type {string}
   * @memberof EligibilityWebsocketEvent
   */
  created_at: string;
  /**
   *
   * @type {string}
   * @memberof EligibilityWebsocketEvent
   */
  session_id?: string;
  /**
   *
   * @type {WebsocketError}
   * @memberof EligibilityWebsocketEvent
   */
  error?: WebsocketError;
  /**
   *
   * @type {string}
   * @memberof EligibilityWebsocketEvent
   */
  card_id?: string;
}

export const EligibilityWebsocketEventTypeEnum = {
  Eligibility: "eligibility",
} as const;

export type EligibilityWebsocketEventTypeEnum =
  (typeof EligibilityWebsocketEventTypeEnum)[keyof typeof EligibilityWebsocketEventTypeEnum];

export type EligibilityWebsocketEvent =
  KeysToCamelCase<EligibilityWebsocketEventSnake>;
