/* tslint:disable */
/* eslint-disable */
/**
 * CardScan API
 * The official documentation for the CardScan API Clients.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



import { KeysToCamelCase, KeysToSnakeCase } from "./";

/**
 * 
 * @export
 * @interface PayerMatchMatchesInnerMetadata
 */
export interface PayerMatchMatchesInnerMetadataOriginal {
    /**
     * 
     * @type {string}
     * @memberof PayerMatchMatchesInnerMetadata
     */
    'last_updated'?: string;
    /**
     * 
     * @type {string}
     * @memberof PayerMatchMatchesInnerMetadata
     */
    'source'?: string;
}
export type PayerMatchMatchesInnerMetadata = KeysToCamelCase<PayerMatchMatchesInnerMetadataOriginal>;
export type PayerMatchMatchesInnerMetadataSnake = KeysToSnakeCase<PayerMatchMatchesInnerMetadataOriginal>;


