/* tslint:disable */
/* eslint-disable */
/**
 * CardScan API
 * The official documentation for the CardScan API.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * PlanStatus - Deprecated please use benefitsInformation
 * @export
 * @interface PlanStatus
 */
export interface PlanStatus {
  /**
   * Loop: 2110C and 2110D, Segments: EB, Element: EB01, Notes: Eligibility or Benefit Information Code
   * @type {string}
   * @memberof PlanStatus
   */
  statusCode?: string;
  /**
   * Loop: 2110C and 2110D, Segments: EB, Element: EB01, Notes: Eligibility or Benefit Information Code Description
   * @type {string}
   * @memberof PlanStatus
   */
  status?: string;
  /**
   * Loop: 2110C and 2110D, Segments: EB, Element: EB05, Notes: Plan Coverage Description
   * @type {string}
   * @memberof PlanStatus
   */
  planDetails?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof PlanStatus
   */
  serviceTypeCodes?: Array<string>;
}
