/* tslint:disable */
/* eslint-disable */
/**
 * CardScan API
 * The official documentation for the CardScan API Clients.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



import { KeysToCamelCase, KeysToSnakeCase } from "./";

/**
 * 
 * @export
 * @interface ResponseMetadata
 */
export interface ResponseMetadataOriginal {
    /**
     * The cursor for the next page of results.
     * @type {string}
     * @memberof ResponseMetadata
     */
    'next_cursor'?: string;
    /**
     * The maximum number of items to return.
     * @type {number}
     * @memberof ResponseMetadata
     */
    'limit'?: number;
    /**
     * The total number of items available.
     * @type {number}
     * @memberof ResponseMetadata
     */
    'total'?: number;
}
export type ResponseMetadata = KeysToCamelCase<ResponseMetadataOriginal>;
export type ResponseMetadataSnake = KeysToSnakeCase<ResponseMetadataOriginal>;


