/* tslint:disable */
/* eslint-disable */
/**
 * CardScan API
 * The official documentation for the CardScan API Clients.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ScanMetadataCaptureScoreScoresInner } from './scan-metadata-capture-score-scores-inner';

import { KeysToCamelCase, KeysToSnakeCase } from "./";

/**
 * 
 * @export
 * @interface ScanMetadataCaptureScore
 */
export interface ScanMetadataCaptureScoreOriginal {
    /**
     * List of capture scores
     * @type {Array<ScanMetadataCaptureScoreScoresInner>}
     * @memberof ScanMetadataCaptureScore
     */
    'scores'?: Array<ScanMetadataCaptureScoreScoresInner>;
    /**
     * Maximum Laplacian score
     * @type {number}
     * @memberof ScanMetadataCaptureScore
     */
    'max_lapScore'?: number;
}
export type ScanMetadataCaptureScore = KeysToCamelCase<ScanMetadataCaptureScoreOriginal>;
export type ScanMetadataCaptureScoreSnake = KeysToSnakeCase<ScanMetadataCaptureScoreOriginal>;


