/* tslint:disable */
/* eslint-disable */
/**
 * CardScan API
 * The official documentation for the CardScan API Clients.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ScanMetadataCameraCapabilitiesAspectRatio } from './scan-metadata-camera-capabilities-aspect-ratio';

import { KeysToCamelCase, KeysToSnakeCase } from "./";

/**
 * Camera capabilities
 * @export
 * @interface ScanMetadataCameraCapabilities
 */
export interface ScanMetadataCameraCapabilitiesOriginal {
    /**
     * 
     * @type {ScanMetadataCameraCapabilitiesAspectRatio}
     * @memberof ScanMetadataCameraCapabilities
     */
    'aspectRatio'?: ScanMetadataCameraCapabilitiesAspectRatio;
    /**
     * 
     * @type {string}
     * @memberof ScanMetadataCameraCapabilities
     */
    'deviceId'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ScanMetadataCameraCapabilities
     */
    'facingMode'?: Array<string>;
    /**
     * 
     * @type {ScanMetadataCameraCapabilitiesAspectRatio}
     * @memberof ScanMetadataCameraCapabilities
     */
    'frameRate'?: ScanMetadataCameraCapabilitiesAspectRatio;
    /**
     * 
     * @type {string}
     * @memberof ScanMetadataCameraCapabilities
     */
    'groupId'?: string;
    /**
     * 
     * @type {ScanMetadataCameraCapabilitiesAspectRatio}
     * @memberof ScanMetadataCameraCapabilities
     */
    'height'?: ScanMetadataCameraCapabilitiesAspectRatio;
    /**
     * 
     * @type {Array<string>}
     * @memberof ScanMetadataCameraCapabilities
     */
    'resizeMode'?: Array<string>;
    /**
     * 
     * @type {ScanMetadataCameraCapabilitiesAspectRatio}
     * @memberof ScanMetadataCameraCapabilities
     */
    'width'?: ScanMetadataCameraCapabilitiesAspectRatio;
}
export type ScanMetadataCameraCapabilities = KeysToCamelCase<ScanMetadataCameraCapabilitiesOriginal>;
export type ScanMetadataCameraCapabilitiesSnake = KeysToSnakeCase<ScanMetadataCameraCapabilitiesOriginal>;


