/* tslint:disable */
/* eslint-disable */
/**
 * CardScan API
 * The official documentation for the CardScan API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ScanMetadataCameraCapabilities } from './scan-metadata-camera-capabilities';
// May contain unused imports in some cases
// @ts-ignore
import { ScanMetadataCaptureCanvas } from './scan-metadata-capture-canvas';
// May contain unused imports in some cases
// @ts-ignore
import { ScanMetadataCaptureScore } from './scan-metadata-capture-score';
// May contain unused imports in some cases
// @ts-ignore
import { ScanMetadataGuides } from './scan-metadata-guides';
// May contain unused imports in some cases
// @ts-ignore
import { ScanMetadataVideoBackground } from './scan-metadata-video-background';
// May contain unused imports in some cases
// @ts-ignore
import { ScanMetadataVideoTrack } from './scan-metadata-video-track';
// May contain unused imports in some cases
// @ts-ignore
import { ScanMetadataWindowInner } from './scan-metadata-window-inner';

import { KeysToCamelCase } from "./";

/**
 * 
 * @export
 * @interface ScanMetadata
 */
export interface ScanMetadataSnake {
    /**
     * The type of capture (automatic or manual)
     * @type {string}
     * @memberof ScanMetadata
     */
    'captureType'?: ScanMetadataCaptureTypeEnum;
    /**
     * 
     * @type {ScanMetadataGuides}
     * @memberof ScanMetadata
     */
    'guides'?: ScanMetadataGuides;
    /**
     * 
     * @type {ScanMetadataCaptureCanvas}
     * @memberof ScanMetadata
     */
    'captureCanvas'?: ScanMetadataCaptureCanvas;
    /**
     * 
     * @type {ScanMetadataVideoBackground}
     * @memberof ScanMetadata
     */
    'videoBackground'?: ScanMetadataVideoBackground;
    /**
     * 
     * @type {ScanMetadataWindowInner}
     * @memberof ScanMetadata
     */
    'windowInner'?: ScanMetadataWindowInner;
    /**
     * Threshold for machine learning
     * @type {number}
     * @memberof ScanMetadata
     */
    'mlThreshold'?: number;
    /**
     * Threshold for Laplacian edge detection
     * @type {number}
     * @memberof ScanMetadata
     */
    'laplacianThreshold'?: number;
    /**
     * Name of the package
     * @type {string}
     * @memberof ScanMetadata
     */
    'package_name'?: string;
    /**
     * Version of the package
     * @type {string}
     * @memberof ScanMetadata
     */
    'package_version'?: string;
    /**
     * 
     * @type {ScanMetadataVideoTrack}
     * @memberof ScanMetadata
     */
    'videoTrack'?: ScanMetadataVideoTrack;
    /**
     * 
     * @type {ScanMetadataCameraCapabilities}
     * @memberof ScanMetadata
     */
    'cameraCapabilities'?: ScanMetadataCameraCapabilities;
    /**
     * 
     * @type {ScanMetadataCaptureScore}
     * @memberof ScanMetadata
     */
    'capture_score'?: ScanMetadataCaptureScore;
}

export const ScanMetadataCaptureTypeEnum = {
    Automatic: 'automatic',
    Manual: 'manual'
} as const;

export type ScanMetadataCaptureTypeEnum = typeof ScanMetadataCaptureTypeEnum[keyof typeof ScanMetadataCaptureTypeEnum];

export type ScanMetadata = KeysToCamelCase<ScanMetadataSnake>;


