/* tslint:disable */
/* eslint-disable */
/**
 * CardScan API
 * The official documentation for the CardScan API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



import { KeysToCamelCase } from "./";

/**
 * Dimensions of the capture canvas
 * @export
 * @interface ScanMetadataCaptureCanvas
 */
export interface ScanMetadataCaptureCanvasSnake {
    /**
     * 
     * @type {number}
     * @memberof ScanMetadataCaptureCanvas
     */
    'width'?: number;
    /**
     * 
     * @type {number}
     * @memberof ScanMetadataCaptureCanvas
     */
    'height'?: number;
}
export type ScanMetadataCaptureCanvas = KeysToCamelCase<ScanMetadataCaptureCanvasSnake>;


