/* tslint:disable */
/* eslint-disable */
/**
 * CardScan API
 * The official documentation for the CardScan API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CoInsurance } from './co-insurance';
// May contain unused imports in some cases
// @ts-ignore
import { CoPayment } from './co-payment';
// May contain unused imports in some cases
// @ts-ignore
import { Deductible } from './deductible';
// May contain unused imports in some cases
// @ts-ignore
import { OOP } from './oop';

import { KeysToCamelCase, KeysToSnakeCase } from "./";

/**
 * 
 * @export
 * @interface Service
 */
export interface ServiceOriginal {
    /**
     * 
     * @type {Deductible}
     * @memberof Service
     */
    'individual_deductible_in_network'?: Deductible;
    /**
     * 
     * @type {Deductible}
     * @memberof Service
     */
    'individual_deductible_out_network'?: Deductible;
    /**
     * 
     * @type {OOP}
     * @memberof Service
     */
    'individual_oop_in_network'?: OOP;
    /**
     * 
     * @type {OOP}
     * @memberof Service
     */
    'individual_oop_out_network'?: OOP;
    /**
     * 
     * @type {Deductible}
     * @memberof Service
     */
    'family_deductible_in_network'?: Deductible;
    /**
     * 
     * @type {Deductible}
     * @memberof Service
     */
    'family_deductible_out_network'?: Deductible;
    /**
     * 
     * @type {OOP}
     * @memberof Service
     */
    'family_oop_in_network'?: OOP;
    /**
     * 
     * @type {OOP}
     * @memberof Service
     */
    'family_oop_out_network'?: OOP;
    /**
     * 
     * @type {CoInsurance}
     * @memberof Service
     */
    'co_insurance_in_network'?: CoInsurance;
    /**
     * 
     * @type {CoInsurance}
     * @memberof Service
     */
    'co_insurance_out_network'?: CoInsurance;
    /**
     * 
     * @type {CoPayment}
     * @memberof Service
     */
    'co_payment_out_network'?: CoPayment;
    /**
     * 
     * @type {CoPayment}
     * @memberof Service
     */
    'co_payment_in_network'?: CoPayment;
    /**
     * The service code.
     * @type {string}
     * @memberof Service
     */
    'service_code'?: string;
}
export type Service = KeysToCamelCase<ServiceOriginal>;
export type ServiceSnake = KeysToSnakeCase<ServiceOriginal>;


