/* tslint:disable */
/* eslint-disable */
/**
 * CardScan API
 * The official documentation for the CardScan API Clients.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



import { KeysToCamelCase, KeysToSnakeCase } from "./";

/**
 * 
 * @export
 * @interface SubscriberDto
 */
export interface SubscriberDtoOriginal {
    /**
     * The subscriber\'s first name. Required and must contain 1-35 alphanumeric characters.  Use this for accurate identification of the subscriber. 
     * @type {string}
     * @memberof SubscriberDto
     */
    'first_name': string;
    /**
     * The subscriber\'s last name. Required and must contain 1-60 alphanumeric characters.  This field is critical for matching subscriber records. 
     * @type {string}
     * @memberof SubscriberDto
     */
    'last_name': string;
    /**
     * The subscriber\'s date of birth, formatted as YYYYMMDD.  Required for validation and eligibility checks.  Example: \'19800101\' 
     * @type {string}
     * @memberof SubscriberDto
     */
    'date_of_birth': string;
}
export type SubscriberDto = KeysToCamelCase<SubscriberDtoOriginal>;
export type SubscriberDtoSnake = KeysToSnakeCase<SubscriberDtoOriginal>;


