/* tslint:disable */
/* eslint-disable */
/**
 * CardScan API
 * The official documentation for the CardScan API.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KeysToCamelCase } from "./";

/**
 *
 * @export
 * @interface ValidateMagicLink200Response
 */
export interface ValidateMagicLink200ResponseSnake {
  /**
   * The token associated with the magic link
   * @type {string}
   * @memberof ValidateMagicLink200Response
   */
  Token: string;
  /**
   * The identity ID.
   * @type {string}
   * @memberof ValidateMagicLink200Response
   */
  IdentityId: string;
}
export type ValidateMagicLink200Response =
  KeysToCamelCase<ValidateMagicLink200ResponseSnake>;
