/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.cardscan.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.cardscan.client.models.Address

class AddressTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Address
        //val modelInstance = Address()

        // to test the property `address1`
        should("test address1") {
            // uncomment below to test the property
            //modelInstance.address1 shouldBe ("TODO")
        }

        // to test the property `address2`
        should("test address2") {
            // uncomment below to test the property
            //modelInstance.address2 shouldBe ("TODO")
        }

        // to test the property `city`
        should("test city") {
            // uncomment below to test the property
            //modelInstance.city shouldBe ("TODO")
        }

        // to test the property `state`
        should("test state") {
            // uncomment below to test the property
            //modelInstance.state shouldBe ("TODO")
        }

        // to test the property `postalCode`
        should("test postalCode") {
            // uncomment below to test the property
            //modelInstance.postalCode shouldBe ("TODO")
        }

    }
}
