/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.cardscan.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.cardscan.client.models.CardApiResponseImages
import ai.cardscan.client.models.CardApiResponseImagesBack
import ai.cardscan.client.models.CardApiResponseImagesFront

class CardApiResponseImagesTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CardApiResponseImages
        //val modelInstance = CardApiResponseImages()

        // to test the property `front`
        should("test front") {
            // uncomment below to test the property
            //modelInstance.front shouldBe ("TODO")
        }

        // to test the property `back`
        should("test back") {
            // uncomment below to test the property
            //modelInstance.back shouldBe ("TODO")
        }

    }
}
