/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.cardscan.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.cardscan.client.models.EligibilityApiResponseEligibilityRequestProvider

class EligibilityApiResponseEligibilityRequestProviderTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EligibilityApiResponseEligibilityRequestProvider
        //val modelInstance = EligibilityApiResponseEligibilityRequestProvider()

        // to test the property `firstName`
        should("test firstName") {
            // uncomment below to test the property
            //modelInstance.firstName shouldBe ("TODO")
        }

        // to test the property `lastName`
        should("test lastName") {
            // uncomment below to test the property
            //modelInstance.lastName shouldBe ("TODO")
        }

        // to test the property `npi`
        should("test npi") {
            // uncomment below to test the property
            //modelInstance.npi shouldBe ("TODO")
        }

    }
}
