/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.cardscan.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.cardscan.client.models.EligibilityApiResponseEligibilityRequestSubscriber

class EligibilityApiResponseEligibilityRequestSubscriberTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EligibilityApiResponseEligibilityRequestSubscriber
        //val modelInstance = EligibilityApiResponseEligibilityRequestSubscriber()

        // to test the property `firstName` - The first name of the subscriber.
        should("test firstName") {
            // uncomment below to test the property
            //modelInstance.firstName shouldBe ("TODO")
        }

        // to test the property `lastName` - The last name of the subscriber.
        should("test lastName") {
            // uncomment below to test the property
            //modelInstance.lastName shouldBe ("TODO")
        }

        // to test the property `memberId` - The member ID of the subscriber.
        should("test memberId") {
            // uncomment below to test the property
            //modelInstance.memberId shouldBe ("TODO")
        }

        // to test the property `dateOfBirth` - The date of birth of the subscriber.
        should("test dateOfBirth") {
            // uncomment below to test the property
            //modelInstance.dateOfBirth shouldBe ("TODO")
        }

    }
}
