/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.cardscan.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.cardscan.client.models.PlanDetails

class PlanDetailsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PlanDetails
        //val modelInstance = PlanDetails()

        // to test the property `planNumber` - The plan number.
        should("test planNumber") {
            // uncomment below to test the property
            //modelInstance.planNumber shouldBe ("TODO")
        }

        // to test the property `groupName` - The name of the group associated with the plan.
        should("test groupName") {
            // uncomment below to test the property
            //modelInstance.groupName shouldBe ("TODO")
        }

        // to test the property `groupNumber` - The group number.
        should("test groupNumber") {
            // uncomment below to test the property
            //modelInstance.groupNumber shouldBe ("TODO")
        }

        // to test the property `planStartDate` - The start date of the plan.
        should("test planStartDate") {
            // uncomment below to test the property
            //modelInstance.planStartDate shouldBe ("TODO")
        }

        // to test the property `planEndDate` - The end date of the plan.
        should("test planEndDate") {
            // uncomment below to test the property
            //modelInstance.planEndDate shouldBe ("TODO")
        }

        // to test the property `planEligibilityStartDate` - The eligibility start date of the plan.
        should("test planEligibilityStartDate") {
            // uncomment below to test the property
            //modelInstance.planEligibilityStartDate shouldBe ("TODO")
        }

        // to test the property `planEligibilityEndDate` - The eligibility end date of the plan.
        should("test planEligibilityEndDate") {
            // uncomment below to test the property
            //modelInstance.planEligibilityEndDate shouldBe ("TODO")
        }

        // to test the property `planName` - The name of the plan.
        should("test planName") {
            // uncomment below to test the property
            //modelInstance.planName shouldBe ("TODO")
        }

        // to test the property `planActive` - Indicates whether the plan is active.
        should("test planActive") {
            // uncomment below to test the property
            //modelInstance.planActive shouldBe ("TODO")
        }

    }
}
