/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.cardscan.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.cardscan.client.models.ResponseMetadata

class ResponseMetadataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ResponseMetadata
        //val modelInstance = ResponseMetadata()

        // to test the property `nextCursor` - The cursor for the next page of results.
        should("test nextCursor") {
            // uncomment below to test the property
            //modelInstance.nextCursor shouldBe ("TODO")
        }

        // to test the property `limit` - The maximum number of items to return.
        should("test limit") {
            // uncomment below to test the property
            //modelInstance.limit shouldBe ("TODO")
        }

        // to test the property `total` - The total number of items available.
        should("test total") {
            // uncomment below to test the property
            //modelInstance.total shouldBe ("TODO")
        }

    }
}
