/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.cardscan.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.cardscan.client.models.ScanMetadataWindowInner

class ScanMetadataWindowInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ScanMetadataWindowInner
        //val modelInstance = ScanMetadataWindowInner()

        // to test the property `width`
        should("test width") {
            // uncomment below to test the property
            //modelInstance.width shouldBe ("TODO")
        }

        // to test the property `height`
        should("test height") {
            // uncomment below to test the property
            //modelInstance.height shouldBe ("TODO")
        }

    }
}
