/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.cardscan.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.cardscan.client.models.ScanMetadataCameraCapabilities
import ai.cardscan.client.models.ScanMetadataCameraCapabilitiesAspectRatio

class ScanMetadataCameraCapabilitiesTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ScanMetadataCameraCapabilities
        //val modelInstance = ScanMetadataCameraCapabilities()

        // to test the property `aspectRatio`
        should("test aspectRatio") {
            // uncomment below to test the property
            //modelInstance.aspectRatio shouldBe ("TODO")
        }

        // to test the property `deviceId`
        should("test deviceId") {
            // uncomment below to test the property
            //modelInstance.deviceId shouldBe ("TODO")
        }

        // to test the property `facingMode`
        should("test facingMode") {
            // uncomment below to test the property
            //modelInstance.facingMode shouldBe ("TODO")
        }

        // to test the property `frameRate`
        should("test frameRate") {
            // uncomment below to test the property
            //modelInstance.frameRate shouldBe ("TODO")
        }

        // to test the property `groupId`
        should("test groupId") {
            // uncomment below to test the property
            //modelInstance.groupId shouldBe ("TODO")
        }

        // to test the property `height`
        should("test height") {
            // uncomment below to test the property
            //modelInstance.height shouldBe ("TODO")
        }

        // to test the property `resizeMode`
        should("test resizeMode") {
            // uncomment below to test the property
            //modelInstance.resizeMode shouldBe ("TODO")
        }

        // to test the property `width`
        should("test width") {
            // uncomment below to test the property
            //modelInstance.width shouldBe ("TODO")
        }

    }
}
