/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.cardscan.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.cardscan.client.models.ValidateMagicLink200Response

class ValidateMagicLink200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ValidateMagicLink200Response
        //val modelInstance = ValidateMagicLink200Response()

        // to test the property `token` - The token associated with the magic link
        should("test token") {
            // uncomment below to test the property
            //modelInstance.token shouldBe ("TODO")
        }

        // to test the property `identityId` - The identity ID.
        should("test identityId") {
            // uncomment below to test the property
            //modelInstance.identityId shouldBe ("TODO")
        }

    }
}
