/* tslint:disable */
/* eslint-disable */
/**
 * CardScan API
 * The official documentation for the CardScan API.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * AdditionalInformation
 * @export
 * @interface AdditionalInformation
 */
export interface AdditionalInformation {
  /**
   * Loop: 2110C and 2110D, Segment: MSG, Element: MSG01, Notes: Message Text Description
   * @type {string}
   * @memberof AdditionalInformation
   */
  description?: string;
}
