/* tslint:disable */
/* eslint-disable */
/**
 * CardScan API
 * The official documentation for the CardScan API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Address } from './address';
// May contain unused imports in some cases
// @ts-ignore
import { ContactInformation } from './contact-information';
// May contain unused imports in some cases
// @ts-ignore
import { ProviderInformation } from './provider-information';

/**
 * BenefitsRelatedEntity
 * @export
 * @interface BenefitsRelatedEntity
 */
export interface BenefitsRelatedEntity {
    /**
     * Loop: 2120C and 2120D, Segments: NM1, Element: NM101, Notes: Entity Identifier Code
     * @type {string}
     * @memberof BenefitsRelatedEntity
     */
    'entityIdentifier'?: string;
    /**
     * Loop: 2120C and 2120D, Segments: NM1, Element: NM102, Notes: Entity Type Qualifier
     * @type {string}
     * @memberof BenefitsRelatedEntity
     */
    'entityType'?: string;
    /**
     * Loop: 2120C and 2120D, Segments: NM1, Element: NM103, Notes: Benefit Related Entity Last or Organization Name
     * @type {string}
     * @memberof BenefitsRelatedEntity
     */
    'entityName'?: string;
    /**
     * Loop: 2120C and 2120D, Segments: NM1, Element: NM104, Notes: Name First
     * @type {string}
     * @memberof BenefitsRelatedEntity
     */
    'entityFirstname'?: string;
    /**
     * Loop: 2120C and 2120D, Segments: NM1, Element: NM105, Notes: Name Middle
     * @type {string}
     * @memberof BenefitsRelatedEntity
     */
    'entityMiddlename'?: string;
    /**
     * Loop: 2120C and 2120D, Segments: NM1, Element: NM107, Notes: Name Suffix
     * @type {string}
     * @memberof BenefitsRelatedEntity
     */
    'entitySuffix'?: string;
    /**
     * Loop: 2120C and 2120D, Segments: NM1, Element: NM108, Notes: Identification Code Qualifier
     * @type {string}
     * @memberof BenefitsRelatedEntity
     */
    'entityIdentification'?: string;
    /**
     * Loop: 2120C and 2120D, Segments: NM1, Element: NM109, Notes: Benefit Related Entity Identifier
     * @type {string}
     * @memberof BenefitsRelatedEntity
     */
    'entityIdentificationValue'?: string;
    /**
     * Loop: 2120C and 2120D, Segments: NM1, Element: NM110, Notes: Entity Relationship Code
     * @type {string}
     * @memberof BenefitsRelatedEntity
     */
    'entityRelationship'?: string;
    /**
     * 
     * @type {Address}
     * @memberof BenefitsRelatedEntity
     */
    'address'?: Address;
    /**
     * 
     * @type {ContactInformation}
     * @memberof BenefitsRelatedEntity
     */
    'contactInformation'?: ContactInformation;
    /**
     * 
     * @type {ProviderInformation}
     * @memberof BenefitsRelatedEntity
     */
    'providerInformation'?: ProviderInformation;
}

