/* tslint:disable */
/* eslint-disable */
/**
 * CardScan API
 * The official documentation for the CardScan API.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Details about any error that occurred during the request. (Only first error)
 * @export
 * @interface EligibilityApiResponseError
 */
export interface EligibilityApiResponseError {
  /**
   * The type of error.
   * @type {string}
   * @memberof EligibilityApiResponseError
   */
  type?: string;
  /**
   * The error code.
   * @type {string}
   * @memberof EligibilityApiResponseError
   */
  code?: string;
  /**
   * A message describing the error.
   * @type {string}
   * @memberof EligibilityApiResponseError
   */
  message?: string;
}
