/* tslint:disable */
/* eslint-disable */
/**
 * CardScan API
 * The official documentation for the CardScan API.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * EligibilityAdditionalInformation
 * @export
 * @interface EligibilityAdditionalInformation
 */
export interface EligibilityAdditionalInformation {
  /**
   * Loop: 2110C and 2110D, Segment: III, Element: III01
   * @type {string}
   * @memberof EligibilityAdditionalInformation
   */
  codeListQualifierCode?: string;
  /**
   * Loop: 2110C and 2110D, Segment: III, Element: III02
   * @type {string}
   * @memberof EligibilityAdditionalInformation
   */
  industryCode?: string;
  /**
   * Loop: 2110C and 2110D, Segment: III, Element: III03
   * @type {string}
   * @memberof EligibilityAdditionalInformation
   */
  codeCategory?: string;
  /**
   * Loop: 2110C and 2110D, Segment: III, Element: III04
   * @type {string}
   * @memberof EligibilityAdditionalInformation
   */
  injuredBodyPartName?: string;
}
