/* tslint:disable */
/* eslint-disable */
/**
 * CardScan API
 * The official documentation for the CardScan API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Address } from './address';

/**
 * Loop: 2100B, Notes: Information Receiver Name
 * @export
 * @interface InformationReceiverName
 */
export interface InformationReceiverName {
    /**
     * Loop: 2100B, Segment: REF, Element: REF02, Notes: REF01=0B State License Number
     * @type {string}
     * @memberof InformationReceiverName
     */
    'stateLicenceNumber'?: string;
    /**
     * Loop: 2100B, Segment: REF, Element: REF02, Notes: REF01=1C Medicare Provider Number
     * @type {string}
     * @memberof InformationReceiverName
     */
    'medicareProviderNumber'?: string;
    /**
     * Loop: 2100B, Segment: REF, Element: REF02, Notes: REF01=1D Medicaid Provider Number
     * @type {string}
     * @memberof InformationReceiverName
     */
    'medicaidProviderNumber'?: string;
    /**
     * Loop: 2100B, Segment: REF, Element: REF02, Notes: REF01=1J Facility ID Number
     * @type {string}
     * @memberof InformationReceiverName
     */
    'facilityIdNumber'?: string;
    /**
     * Loop: 2100B, Segment: REF, Element: REF02, Notes: REF01=CT Contact Number
     * @type {string}
     * @memberof InformationReceiverName
     */
    'contactNumber'?: string;
    /**
     * Loop: 2100B, Segment: REF, Element: REF02, Notes: REF01=EL Electronic Device Pin Number
     * @type {string}
     * @memberof InformationReceiverName
     */
    'devicePinNumber'?: string;
    /**
     * Loop: 2100B, Segment: REF, Element: REF02, Notes: REF01=EO Submitter Identification Number
     * @type {string}
     * @memberof InformationReceiverName
     */
    'submitterIdNumber'?: string;
    /**
     * Loop: 2100B, Segment: REF, Element: REF02, Notes: REF01=HPI Centers for Medicare and Medicaid Services National Provider Identifier
     * @type {string}
     * @memberof InformationReceiverName
     */
    'nationalProviderIdentifier'?: string;
    /**
     * Loop: 2100B, Segment: REF, Element: REF02, Notes: REF01=N5 Provider Plan Network Identification Number
     * @type {string}
     * @memberof InformationReceiverName
     */
    'providerPlanNetworkIdNumber'?: string;
    /**
     * Loop: 2100B, Segment: REF, Element: REF02, Notes: REF01=N7 Facility Network Identification Number
     * @type {string}
     * @memberof InformationReceiverName
     */
    'facilityNetworkIdNumber'?: string;
    /**
     * Loop: 2100B, Segment: REF, Element: REF02, Notes: REF01=Q4 Prior Identifier Number
     * @type {string}
     * @memberof InformationReceiverName
     */
    'priorIdentifierNumber'?: string;
    /**
     * Loop: 2100B, Segment: REF, Element: REF02, Notes: REF01=SY Social Security Number
     * @type {string}
     * @memberof InformationReceiverName
     */
    'socialSecurityNumber'?: string;
    /**
     * Loop: 2100B, Segment: REF, Element: REF02, Notes: REF01=TJ Federal Taxpayer\'s Identification Number
     * @type {string}
     * @memberof InformationReceiverName
     */
    'federalTaxpayerIdentificationNumber'?: string;
    /**
     * Loop: 2100B, Segment: REF, Element: REF03, Notes: REF01=0B REF02=stateLicenceNumber Federal Taxpayer\'s Identification Number
     * @type {string}
     * @memberof InformationReceiverName
     */
    'informationReceiverAdditionalIdentifierState'?: string;
    /**
     * 
     * @type {Address}
     * @memberof InformationReceiverName
     */
    'address'?: Address;
}

