/* tslint:disable */
/* eslint-disable */
/**
 * CardScan API
 * The official documentation for the CardScan API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Loop: 2110C and 2110D, Notes: Eligibility or Benefit Information, EQ02 and beyond only
 * @export
 * @interface MedicalProcedure
 */
export interface MedicalProcedure {
    /**
     * Loop: 2110C and 2110D, Segment: EQ, Element: EQ02-1, Notes: Composite Medical Procedure Identifier - Product or Service ID Qualifier, Allowed Values are: \'AD\' American Dental Association Codes, \'CJ\' Current Procedural Terminology (CPT) Codes, \'HC\' Health Care Financing Administration Common Procedural Coding System (HCPCS) Codes, \'ID\' International Classification of Diseases, 9th Revision, Clinical Modification (ICD-9-CM) - Procedure, \'IV\' Home Infusion EDI Coalition (HIEC) Product/Service Code, \'N4\' National Drug Code in 5-4-2 Format, \'ZZ\' Mutually Defined
     * @type {string}
     * @memberof MedicalProcedure
     */
    'productOrServiceIDQualifier'?: MedicalProcedureProductOrServiceIDQualifierEnum;
    /**
     * Loop: 2110C and 2110D, Segment: EQ, Element: EQ02-2, Notes: Composite Medical Procedure Identifier - Procedure Code
     * @type {string}
     * @memberof MedicalProcedure
     */
    'procedureCode'?: string;
    /**
     * Loop: 2110C and 2110D, Segment: EQ, Element: EQ02-3, Notes: Composite Medical Procedure Identifier - Procedure Modifier
     * @type {Array<string>}
     * @memberof MedicalProcedure
     */
    'procedureModifiers'?: Array<string>;
    /**
     * Loop: 2110C and 2110D, Segment: EQ, Element: EQ05, Notes: Composite Diagnosis Code Pointer
     * @type {Array<string>}
     * @memberof MedicalProcedure
     */
    'diagnosisCodePointer'?: Array<string>;
}

export const MedicalProcedureProductOrServiceIDQualifierEnum = {
    Ad: 'AD',
    Cj: 'CJ',
    Hc: 'HC',
    Id: 'ID',
    Iv: 'IV',
    N4: 'N4',
    Zz: 'ZZ'
} as const;

export type MedicalProcedureProductOrServiceIDQualifierEnum = typeof MedicalProcedureProductOrServiceIDQualifierEnum[keyof typeof MedicalProcedureProductOrServiceIDQualifierEnum];


