/* tslint:disable */
/* eslint-disable */
/**
 * CardScan API
 * The official documentation for the CardScan API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Meta data about the response
 * @export
 * @interface MetaData
 */
export interface MetaData {
    /**
     * Sender id assigned to this request
     * @type {string}
     * @memberof MetaData
     */
    'senderId'?: string;
    /**
     * Submitter id assigned to this request
     * @type {string}
     * @memberof MetaData
     */
    'submitterId'?: string;
    /**
     * Billing id assigned to this request
     * @type {string}
     * @memberof MetaData
     */
    'billerId'?: string;
    /**
     * Used by Change Healthcare to identify where this request can be found for support
     * @type {string}
     * @memberof MetaData
     */
    'applicationMode'?: string;
    /**
     * Unique Id assigned to each request by Change Healthcare
     * @type {string}
     * @memberof MetaData
     */
    'traceId'?: string;
    /**
     * BHT03 Value for submitterTransactionIdentifier
     * @type {string}
     * @memberof MetaData
     */
    'outboundTraceId'?: string;
}

