/* tslint:disable */
/* eslint-disable */
/**
 * CardScan API
 * The official documentation for the CardScan API.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ScanMetadataCameraCapabilitiesAspectRatio
 */
export interface ScanMetadataCameraCapabilitiesAspectRatio {
  /**
   *
   * @type {number}
   * @memberof ScanMetadataCameraCapabilitiesAspectRatio
   */
  max?: number;
  /**
   *
   * @type {number}
   * @memberof ScanMetadataCameraCapabilitiesAspectRatio
   */
  min?: number;
}
