# coding: utf-8

"""
    CardScan API

    The official documentation for the CardScan API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.contact_information import ContactInformation  # noqa: E501

class TestContactInformation(unittest.TestCase):
    """ContactInformation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContactInformation:
        """Test ContactInformation
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContactInformation`
        """
        model = ContactInformation()  # noqa: E501
        if include_optional:
            return ContactInformation(
                name = '',
                contacts = [
                    openapi_client.models.contacts.Contacts(
                        communication_mode = '', 
                        communication_number = '', )
                    ]
            )
        else:
            return ContactInformation(
        )
        """

    def testContactInformation(self):
        """Test ContactInformation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
