/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CardResponseMetadata

class CardResponseMetadataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CardResponseMetadata
        //val modelInstance = CardResponseMetadata()

        // to test the property `insuranceScanVersion`
        should("test insuranceScanVersion") {
            // uncomment below to test the property
            //modelInstance.insuranceScanVersion shouldBe ("TODO")
        }

        // to test the property `payerMatchVersion`
        should("test payerMatchVersion") {
            // uncomment below to test the property
            //modelInstance.payerMatchVersion shouldBe ("TODO")
        }

    }
}
