/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CoverageSummary
import org.openapitools.client.models.Deductible
import org.openapitools.client.models.OOP

class CoverageSummaryTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CoverageSummary
        //val modelInstance = CoverageSummary()

        // to test the property `individualDeductibleInNetwork`
        should("test individualDeductibleInNetwork") {
            // uncomment below to test the property
            //modelInstance.individualDeductibleInNetwork shouldBe ("TODO")
        }

        // to test the property `individualOopInNetwork`
        should("test individualOopInNetwork") {
            // uncomment below to test the property
            //modelInstance.individualOopInNetwork shouldBe ("TODO")
        }

        // to test the property `familyDeductibleInNetwork`
        should("test familyDeductibleInNetwork") {
            // uncomment below to test the property
            //modelInstance.familyDeductibleInNetwork shouldBe ("TODO")
        }

        // to test the property `familyOopInNetwork`
        should("test familyOopInNetwork") {
            // uncomment below to test the property
            //modelInstance.familyOopInNetwork shouldBe ("TODO")
        }

    }
}
