/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CreateCardRequest
import org.openapitools.client.models.CreateCardRequestBackside

class CreateCardRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateCardRequest
        //val modelInstance = CreateCardRequest()

        // to test the property `enableBacksideScan` - Whether to enable backside scanning
        should("test enableBacksideScan") {
            // uncomment below to test the property
            //modelInstance.enableBacksideScan shouldBe ("TODO")
        }

        // to test the property `enableLivescan` - Whether to enable live scanning
        should("test enableLivescan") {
            // uncomment below to test the property
            //modelInstance.enableLivescan shouldBe ("TODO")
        }

        // to test the property `backside`
        should("test backside") {
            // uncomment below to test the property
            //modelInstance.backside shouldBe ("TODO")
        }

    }
}
