/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CreateCardRequestBackside

class CreateCardRequestBacksideTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateCardRequestBackside
        //val modelInstance = CreateCardRequestBackside()

        // to test the property `scanning` - The scanning mode
        should("test scanning") {
            // uncomment below to test the property
            //modelInstance.scanning shouldBe ("TODO")
        }

    }
}
