/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.EligibilityError

class EligibilityErrorTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EligibilityError
        //val modelInstance = EligibilityError()

        // to test the property ``field`` - The field that caused the error.
        should("test `field`") {
            // uncomment below to test the property
            //modelInstance.`field` shouldBe ("TODO")
        }

        // to test the property `code` - The error code.
        should("test code") {
            // uncomment below to test the property
            //modelInstance.code shouldBe ("TODO")
        }

        // to test the property `description` - A description of the error.
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `followupAction` - Suggested follow-up action for the error.
        should("test followupAction") {
            // uncomment below to test the property
            //modelInstance.followupAction shouldBe ("TODO")
        }

        // to test the property `location` - The location of the error.
        should("test location") {
            // uncomment below to test the property
            //modelInstance.location shouldBe ("TODO")
        }

        // to test the property `possibleResolutions` - Possible resolutions for the error.
        should("test possibleResolutions") {
            // uncomment below to test the property
            //modelInstance.possibleResolutions shouldBe ("TODO")
        }

    }
}
