/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.EligibilityApiResponse
import org.openapitools.client.models.EligibilityApiResponseEligibilityRequest
import org.openapitools.client.models.EligibilityApiResponseError

class EligibilityApiResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EligibilityApiResponse
        //val modelInstance = EligibilityApiResponse()

        // to test the property `eligibilityId` - The ID of the eligibility record.
        should("test eligibilityId") {
            // uncomment below to test the property
            //modelInstance.eligibilityId shouldBe ("TODO")
        }

        // to test the property `state` - The state of the eligibility record.
        should("test state") {
            // uncomment below to test the property
            //modelInstance.state shouldBe ("TODO")
        }

        // to test the property `cardId` - The ID of the card.
        should("test cardId") {
            // uncomment below to test the property
            //modelInstance.cardId shouldBe ("TODO")
        }

        // to test the property `createdAt` - The timestamp when the eligibility record was created.
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `updateAt` - The timestamp when the eligibility record was last updated.
        should("test updateAt") {
            // uncomment below to test the property
            //modelInstance.updateAt shouldBe ("TODO")
        }

        // to test the property `eligibilityRequest`
        should("test eligibilityRequest") {
            // uncomment below to test the property
            //modelInstance.eligibilityRequest shouldBe ("TODO")
        }

        // to test the property `eligibilityResponse` - The eligibility raw response.
        should("test eligibilityResponse") {
            // uncomment below to test the property
            //modelInstance.eligibilityResponse shouldBe ("TODO")
        }

        // to test the property `eligibilitySummarizedResponse` - The eligibility summarized response.
        should("test eligibilitySummarizedResponse") {
            // uncomment below to test the property
            //modelInstance.eligibilitySummarizedResponse shouldBe ("TODO")
        }

        // to test the property `error`
        should("test error") {
            // uncomment below to test the property
            //modelInstance.error shouldBe ("TODO")
        }

    }
}
