/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.EnrichedCopayResultInner
import org.openapitools.client.models.CopayCategory
import org.openapitools.client.models.CopayDeductibleService

class EnrichedCopayResultInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EnrichedCopayResultInner
        //val modelInstance = EnrichedCopayResultInner()

        // to test the property `service`
        should("test service") {
            // uncomment below to test the property
            //modelInstance.service shouldBe ("TODO")
        }

        // to test the property `category`
        should("test category") {
            // uncomment below to test the property
            //modelInstance.category shouldBe ("TODO")
        }

        // to test the property ``value`` - The copay/deductible amount as a number
        should("test `value`") {
            // uncomment below to test the property
            //modelInstance.`value` shouldBe ("TODO")
        }

        // to test the property `score` - Confidence score for the extraction (0-1 as string)
        should("test score") {
            // uncomment below to test the property
            //modelInstance.score shouldBe ("TODO")
        }

    }
}
