/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.WebhookCardCompletedEvent
import org.openapitools.client.models.WebhookCardCompletedEventConfiguration

class WebhookCardCompletedEventTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WebhookCardCompletedEvent
        //val modelInstance = WebhookCardCompletedEvent()

        // to test the property `cardId` - Unique identifier for the created card.
        should("test cardId") {
            // uncomment below to test the property
            //modelInstance.cardId shouldBe ("TODO")
        }

        // to test the property `configuration`
        should("test configuration") {
            // uncomment below to test the property
            //modelInstance.configuration shouldBe ("TODO")
        }

        // to test the property `createdAt` - Timestamp for when the card was created.
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `deleted` - Flag indicating whether the card is deleted.
        should("test deleted") {
            // uncomment below to test the property
            //modelInstance.deleted shouldBe ("TODO")
        }

        // to test the property `sessionId` - Unique identifier for the session.
        should("test sessionId") {
            // uncomment below to test the property
            //modelInstance.sessionId shouldBe ("TODO")
        }

        // to test the property `type` - Type of event.
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `updatedAt` - Timestamp for the last update to the card record.
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property `userId` - Identifier for the user associated with the event.
        should("test userId") {
            // uncomment below to test the property
            //modelInstance.userId shouldBe ("TODO")
        }

    }
}
