name: Publish Package to pub.dev

on:
  workflow_dispatch:
  push:
    tags:
      - 'dart-v*'

jobs:
  publish-dart-package:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: clients/cardscan-dart
    steps:
    - uses: actions/checkout@v4
    - uses: dart-lang/setup-dart@v1
    - name: Install dependencies
      run: dart pub get
    - name: Publish to pub.dev
      run: dart pub publish --force
    - name: Notify slack fail
      if: failure()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: devops-monitoring
        status: FAILED
        color: danger
