name: Publish Package to pub.dev

on:
  workflow_dispatch:
  repository_dispatch:
    types: [publish-dart]

jobs:
  publish-dart-package:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Publish Dart package"
        uses: k-paxian/dart-package-publisher@master
        with:
          accessToken: ${{ secrets.DART_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.DART_REFRESH_TOKEN }}
          relativePath: "clients/cardscan-dart"

      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: devops-monitoring
          status: FAILED
          color: danger
