name: Re-generate API Clients

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  check_changes:
    runs-on: ubuntu-latest
    permissions: read-all
    outputs:
      changes: ${{ steps.filter.outputs.changes }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          changes:
            - 'openapi.yaml'
            - 'openapi-generator-configs/*.config.json'
            - 'templates/*-template/*'

  generate-and-commit:
    needs: check_changes
    if: ${{ needs.check_changes.outputs.changes == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main

    - name: Generate TypeScript Client
      uses: openapi-generators/openapitools-generator-action@v1
      with:
        generator: typescript-axios
        openapi-file: openapi.yaml
        config-file: openapi-generator-configs/ts.config.json
        template-dir: templates/typescript-template
        command-args: -o clients/cardscan-ts
        generator-tag: v7.7.0

    - name: Generate Python Client
      uses: openapi-generators/openapitools-generator-action@v1
      with:
        generator: python-pydantic-v1
        openapi-file: openapi.yaml
        config-file: openapi-generator-configs/python.config.json
        template-dir: templates/python-template
        command-args: -o clients/cardscan-python
        generator-tag: v7.7.0

    - name: Generate Swift Client
      uses: openapi-generators/openapitools-generator-action@v1
      with:
        generator: swift5
        openapi-file: openapi.yaml
        config-file: openapi-generator-configs/swift.config.json
        command-args: -o clients/cardscan-swift
        generator-tag: v7.7.0

    - name: Generate Dart Client
      uses: openapi-generators/openapitools-generator-action@v1
      with:
        generator: dart-dio
        openapi-file: openapi.yaml
        config-file: openapi-generator-configs/dart.config.json
        command-args: -o clients/cardscan-dart
        generator-tag: v7.7.0

    - name: Generate Kotlin Client
      uses: openapi-generators/openapitools-generator-action@v1
      with:
        generator: kotlin
        openapi-file: openapi.yaml
        command-args: -o clients/cardscan-kotlin
        generator-tag: v7.7.0

    - name: Commit Changes
      if: ${{ github.event_name == 'push' }}
      run: |-
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add clients/
        git commit -m 'chore: re-generate clients'
        git push origin main
