name: Re-generate API Clients

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  check_pr_type:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
    - id: check
      run: |
        if [[ "${{ github.event_name }}" == "push" && "${{ contains(github.event.head_commit.message, 'chore/re-generate-clients') }}" == "true" ]]; then
          echo "should_run=false" >> $GITHUB_OUTPUT
        elif [[ "${{ github.event_name }}" == "pull_request" && "${{ contains(github.event.pull_request.labels.*.name, 'client-generation') }}" == "true" ]]; then
          echo "should_run=false" >> $GITHUB_OUTPUT
        else
          echo "should_run=true" >> $GITHUB_OUTPUT
        fi

  check_changes:
    needs: check_pr_type
    if: needs.check_pr_type.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    permissions: read-all
    outputs:
      changes: ${{ steps.filter.outputs.changes }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          changes:
            - 'openapi.yaml'
            - 'openapi-generator-configs/*.config.json'
            - 'templates/*-template/*'

  generate-clients:
    needs: [check_pr_type, check_changes]
    if: needs.check_pr_type.outputs.should_run == 'true' && needs.check_changes.outputs.changes == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v3
    - name: Generate TypeScript Client
      uses: openapi-generators/openapitools-generator-action@v1
      with:
        generator: typescript-axios
        openapi-file: openapi.yaml
        config-file: openapi-generator-configs/ts.config.json
        template-dir: templates/typescript-template
        command-args: -o clients/cardscan-ts
        generator-tag: v7.7.0

    - name: Generate Python Client
      uses: openapi-generators/openapitools-generator-action@v1
      with:
        generator: python-pydantic-v1
        openapi-file: openapi.yaml
        config-file: openapi-generator-configs/python.config.json
        template-dir: templates/python-template
        command-args: -o clients/cardscan-python
        generator-tag: v7.7.0

    - name: Generate Swift Client
      uses: openapi-generators/openapitools-generator-action@v1
      with:
        generator: swift5
        openapi-file: openapi.yaml
        config-file: openapi-generator-configs/swift.config.json
        command-args: -o clients/cardscan-swift
        generator-tag: v7.7.0

    - name: Generate Dart Client
      uses: openapi-generators/openapitools-generator-action@v1
      with:
        generator: dart-dio
        openapi-file: openapi.yaml
        config-file: openapi-generator-configs/dart.config.json
        command-args: -o clients/cardscan-dart
        generator-tag: v7.7.0

    - name: Generate Kotlin Client
      uses: openapi-generators/openapitools-generator-action@v1
      with:
        generator: kotlin
        openapi-file: openapi.yaml
        command-args: -o clients/cardscan-kotlin
        generator-tag: v7.7.0

    - name: Create Pull Request
      if: ${{ github.event_name == 'push' && needs.check_changes.outputs.changes == 'true' }}
      uses: peter-evans/create-pull-request@v7
      with:
        title: Re-generate API clients
        reviewers: nickls,zcyllainowu
        assignees: nickls,zcyllainowu
        commit-message: 'chore: re-generate API clients'
        delete-branch: true
        body: |
          This PR updates the generated API clients based on changes to:
          - OpenAPI specification
          - Generator configurations
          - Templates

          This PR was automatically created because changes were detected in the main branch that affect client generation.
        branch: chore/re-generate-clients-${{ github.run_number }}
        base: main
        labels: automated-pr,client-generation
