name: Test clients generation

on:
  pull_request:
    branches: [main]

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      oas_changed: ${{ steps.filter.outputs.oas_changed }}
      config_changed: ${{ steps.filter.outputs.config_changed }}
      templates_changed: ${{ steps.filter.outputs.templates_changed }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          oas_changed:
            - 'openapi.yaml'
          config_changed:
            - 'openapi-generator-configs/*'
          templates_changed:
            - 'templates/*'
  generate-ts-client:
    runs-on: ubuntu-latest
    needs: check_changes
    if: ${{ needs.check_changes.outputs.oas_changed == 'true' || needs.check_changes.outputs.config_changed == 'true' || needs.check_changes.outputs.templates_changed == 'true' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Generate Typescript Client
      uses: openapi-generators/openapitools-generator-action@v1
      with:
        generator: typescript-axios
        openapi-file: openapi.yaml
        config-file: openapi-generator-configs/ts.config.json
        template-dir: templates/typescript-template

  generate-python-client:
    runs-on: ubuntu-latest
    needs: check_changes
    if: ${{ needs.check_changes.outputs.oas_changed == 'true' || needs.check_changes.outputs.config_changed == 'true' || needs.check_changes.outputs.templates_changed == 'true' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Generate Python Client
      uses: openapi-generators/openapitools-generator-action@v1
      with:
        generator: python-pydantic-v1
        openapi-file: openapi.yaml
        config-file: openapi-generator-configs/python.config.json
        template-dir: templates/python-template
