name: Test build

on:
  pull_request:
    branches: [main]

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      oas_changed: ${{ steps.filter.outputs.oas }}
      ts_changed: ${{ steps.filter.outputs.ts }}
      py_changed: ${{ steps.filter.outputs.py }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          ts:
            - 'clients/cardscan-ts/**/*.ts'
          py:
            - 'clients/cardscan-python/**/*.py'
          oas:
            - 'openapi.yaml'
  build-test-ts:
    runs-on: ubuntu-latest
    needs: check_changes
    if: ${{ needs.check_changes.outputs.ts_changed == 'true' || needs.check_changes.outputs.oas_changed == 'true' }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.x
    - name: Install dependencies
      working-directory: clients/cardscan-ts
      run: npm ci
    - name: Test build
      working-directory: clients/cardscan-ts
      run: npm run build

  build-test-python:
    runs-on: ubuntu-latest
    needs: check_changes
    if: ${{ needs.check_changes.outputs.py_changed == 'true' || needs.check_changes.outputs.oas_changed == 'true' }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - name: Setup poetry
      uses: Gr1N/setup-poetry@v8
      with:
        poetry-version: 1.2.2
    - name: Install dependencies
      working-directory: clients/cardscan-python
      run: poetry install
    - name: Test build
      working-directory: clients/cardscan-python
      run: poetry build
  set-check-run:
    runs-on: ubuntu-latest
    if: ${{ needs.check_changes.outputs.py_changed == 'true' }}
    steps:
    - name: Create a check run for build-test-python
      uses: peter-evans/create-check@v3
      with:
        check-name: build-test-python
        status: completed
        conclusion: success
        output-title: Skipped
        output-summary: No changes detected in Python files.
